name: Actualizar Base de Datos

on:
  schedule:
    - cron: '45 13 * * *' #Establezco el cron para que se me actualice mi base de datos MySQL

jobs:
  actualizar_bd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - run: python -m pip install virtualenv

      - run: python -m virtualenv env

      - run: |
          source DataCollections/env/bin/activate
          pip install -r DataCollections/requirements.txt


      - name: Run data.py script
        run: |
          source DataCollections/env/bin/activate
          python DataCollections/Data/data.py  
