name: Actualizar Base de Datos

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  actualizar_bd:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.2'

      - name: Instalo las dependencias
        run: |
          pip install -r DataCollections\requirements.txt

      - name: Configuro PYTHONPATH
        run: |
          $env:PYTHONPATH += ";${env:PYTHONPATH};${env:GITHUB_WORKSPACE}/DataCollections"

      - name: Ejecuto el script data.py
        run: |
          python DataCollections\Scrapers\ScrapingUBU\scrapingUBU.py

