name: Actualizar Base de Datos

on:
  schedule:
    - cron: '40 12 * * *' #Establezco el cron para que se me actualice mi base de datos MySQL

jobs:
  actualizar_bd:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x' 

      - run: python -m pip install virtualenv

      - run: python -m virtualenv env

      - run: |
          .\env\Scripts\activate  
          pip install -r DataCollections\requirements.txt

      - name: Run data.py script
        run: python DataCollections\Data\data.py
