name: Actualizar suscripciones

on:
  schedule:
    - cron: '0 0 5 * *'

jobs:
  actualizar_bd:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.2'

      - name: Instalo las dependencias
        run: |
          pip install -r DataCollections\requirements.txt

      - name: Ejecuto el script data.py
        run: |
          python DataCollections/Data/reiniciar_suscripciones.py 

